apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  creationTimestamp: null
  name: carts-db
spec:
  gateways:
  - sockshop-dev-gateway.sockshop-dev
  - mesh
  hosts:
  - carts-db.sockshop-dev.westernunion.workshop.keptn.sh
  - carts-db
  http:
  - route:
    - destination:
        host: carts-db.sockshop-dev.svc.cluster.local
